name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install `gh-pages`
      run: npm install -g gh-pages

    - name: Deploy to GitHub Pages
      run: |
        mkdir -p public
        cp hello.html public/
        cd public
        git init
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy to GitHub Pages"
        git remote add origin https://github.com/${{ github.io/Atividade_Daniela/ }}.git
        git push --force --set-upstream origin master:gh-pages
